version: '3.8'

services:
  api:
    image: backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      DB_HOST: db
    depends_on:
      db: 
        condition: service_healthy
    networks:
      - local

  frontend:
    image: frontend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - frontend:/app/front
      - frontend:/app/front/node_modules
    ports:
      - '8000:8000'
    environment:  
      - BACKEND_URL=http://localhost/3000
    networks:
      - local

  db:
    image: mysql:8.2
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db 
      PMA_USER: root 
      PMA_PASSWORD: rootpassword 
    ports:
      - "8080:80" 
    depends_on:
      - db 
    networks:
      - local
    restart: unless-stopped
    
volumes:
  mysql_data:
  node:
  frontend:
  
networks:
  local: