version: '3.8'

services:
  app:
    image: test
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
      DB_HOST: db
    depends_on:
      db: 
        condition: service_healthy


  db:
    image: mysql:8.2
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql_data:
  node:
