version: '3.2'

networks:
  wordpress-network: 

volumes:
  wordpress:
  wordpressdb:
  
services:

  wordpress:
    image: wordpress
    restart: always
    networks: 
      - wordpress-network
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wordpressdb3
    volumes:
      - wordpress:/var/www/html

  wordpressdb:
    image: mysql:5.7
    restart: always
    networks: 
      - wordpress-network
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wordpressdb:/var/lib/mysql
